# Generated by Django 5.0.4 on 2024-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_productrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
