# Generated by Django 5.0.2 on 2024-05-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
