# Generated by Django 5.0.2 on 2024-05-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
