# Generated by Django 5.0.2 on 2024-05-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
