# Generated by Django 5.0.2 on 2024-05-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
